image: Visual Studio 2015

branches:
  only:
    - master

install:
  - npm i
  - del *.tgz /F /Q
  - npm run clean
  - npm run config

build: off

test_script:
  - npm run node-gyp:binding
  - npm run node-gyp:configure
  - npm run node-gyp:build
  - npm run cleanup
  - npm pack

artifacts:
  - path: '*.tgz'

shallow_clone: true
